#!/bin/sh
CONTAINER="registry.appbucket.io/odin/odin-analytics:latest"
COMMAND="python3 /home/user/build/odin/scripts/python/rfj_alerts/rfj_keyword_alerts.py"

docker pull ${CONTAINER}

docker run --rm -t -v ${HOME}/.odin:/home/user/.odin \
                    -v ${HOME}/projects/odin/rfj_alerting_app/data/model:/home/user/projects/odin/rfj_alerting_app/data/model ${CONTAINER} bash -c "${COMMAND}"

