name: Docker Image CI

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

  pull_request:
    branches: [ "master" ]

env:
  IMAGE_NAME: odin-analytics
  REGISTRY_NAME: odin
  DOCKER_BUILDKIT: 1
jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        run: bash ./docker-test.sh


  build-push:

    runs-on: ubuntu-latest

    steps:
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_ENDPOINT }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_ENDPOINT }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME}}:latest



