name: Docker Image CI

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: bash ./docker-build.sh


#  deploy:
#    needs: build
#    runs-on: ubunto-lastes
#    steps:
#      - name: Checkout Files
#        uses: actions/checkout@v3
#
#      - name: Get tag name
#        uses: olegtarsov/get-tag@v2
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Load DO
#      env:
#        THIS_TEST: ${{ secrets.THIS_IS_SECRET }}
#      run: |
#        echo "$THIS_TEST"
